// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8i-7UMfsBXPzgfc0L4zQw7ZnzzXu0Khw',
    appId: '1:20208301176:web:b5284d85214023f739298d',
    messagingSenderId: '20208301176',
    projectId: 'elaunch-management',
    authDomain: 'elaunch-management.firebaseapp.com',
    storageBucket: 'elaunch-management.firebasestorage.app',
    measurementId: 'G-TK5W62383E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjUHJfyCsF-ERBkeGStMWWOx29ngRI7zc',
    appId: '1:20208301176:android:b829ffbaa81d645139298d',
    messagingSenderId: '20208301176',
    projectId: 'elaunch-management',
    storageBucket: 'elaunch-management.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeH83LRczmGVNbdUSXEWghHDJ5zitdmTE',
    appId: '1:20208301176:ios:e914aa8a89109b8839298d',
    messagingSenderId: '20208301176',
    projectId: 'elaunch-management',
    storageBucket: 'elaunch-management.firebasestorage.app',
    iosBundleId: 'com.example.elaunchManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeH83LRczmGVNbdUSXEWghHDJ5zitdmTE',
    appId: '1:20208301176:ios:e914aa8a89109b8839298d',
    messagingSenderId: '20208301176',
    projectId: 'elaunch-management',
    storageBucket: 'elaunch-management.firebasestorage.app',
    iosBundleId: 'com.example.elaunchManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8i-7UMfsBXPzgfc0L4zQw7ZnzzXu0Khw',
    appId: '1:20208301176:web:21f711d8eb16922639298d',
    messagingSenderId: '20208301176',
    projectId: 'elaunch-management',
    authDomain: 'elaunch-management.firebaseapp.com',
    storageBucket: 'elaunch-management.firebasestorage.app',
    measurementId: 'G-SX48JYZHSY',
  );
}
